### PR TITLE
:beetle: Bug/saving

### PR DESCRIPTION
**Pull request by AlexandreSajus**
"Save as" now actually saves the .ipyg file instead of just setting the savepath

Default file suffix is set to .ipyg:
image

### CODE REVIEW

**Comment by AlexandreSajus** [comment]
"run source code when run button is pressed." fails on Github but succeeds in local. Weird, especially since this has happened on another completely different branch

**Comment by MathisFederico** [comment]
> "run source code when run button is pressed." fails on Github but succeeds in local. Weird, especially since this has happened on another completely different branch

Yeah yeah I know ..

**Review by MathisFederico — DISMISSED** [review]
Does this solve #106 ?
If yes, link the issue and merge !

**Comment by MathisFederico** [comment]
> Does this solve #106 ? If yes, link the issue and merge !

Well a fix to #106 has been merge (thanks @FabienRoger !), just make it compatible while solving conflicts !

**Comment by FabienRoger** [comment]
This branch fixes #106 but also another one. I will merge them so that both are fixed.

**Review by MathisFederico — APPROVED** [review]

**Pull request merged**
